name: Setup .NET

on:
  push:
    branches: [master]

jobs:
  setup-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore .NET dependencies
        run: dotnet restore ./Backend/FlashcardBackend.csproj

      - name: Build .NET project
        run: dotnet build ./Backend/FlashcardBackend.csproj --configuration Release

      - name: Publish .NET project
        run: dotnet publish ./Backend/FlashcardBackend.csproj --configuration Release --output ./publish
